[package]
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"
name = "terracheck"
version = "0.1.0"
[build-dependencies]
cc = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dependencies]
glob = "*"
tree-sitter = "*"
argh = "0.1"
colored = "2.*"
pulldown-cmark = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
