[package]
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"
name = "terraform"
version = "0.0.1"

[dependencies]
tree-sitter = "0.17.0"

[build-dependencies]
cc = "1.0.61"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"

